[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapDistributed = "f9701e48-63b3-45aa-9a63-9bc6c271f355"
GridapPETSc = "bcdc36c2-0c3e-11ea-095a-c9dadae499f1"
GridapSolvers = "6d3209ee-5e3c-4db7-a716-942eb12ed534"
HyperFEM = "ddbf423a-3df4-409e-9685-3dc416cae46c"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
MultiAssign = "5e2c8b86-4afa-40de-bd09-d9d381e5dc2b"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[sources]
HyperFEM = {path = "..\\HyperFEM"}
