[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapSolvers = "6d3209ee-5e3c-4db7-a716-942eb12ed534"
HyperFEM = "ddbf423a-3df4-409e-9685-3dc416cae46c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
